default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flatiron_students_development

test:
  <<: *default
  database: flatiron_students_test

production:
  <<: *default
  database: flatiron_students_production
  username: flatiron_students
  password: <%= ENV['FLATIRON_STUDENTS_DATABASE_PASSWORD'] %>
